import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
to print the data types of both the variables.

In [5]:
#Ans1.
# Yes , there is a difference in the data type of the list_and array_list variables.list_ is the list of string while  array_ list is the Numpy array  of string.

import numpy as np 
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and 
arra_list.

In [6]:
#Ans2.
import numpy as np 
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types of each element in list_
for element in list_ :
    print(type(element))

# Print data type of each element in array_list
for element in array_list :
    print(type(element))





<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and 
arra_list? If so then print the data types of each and every element present in both the variables, list_ 
and arra_list.

Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [8]:
#Ans3.
import numpy as np 

array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
for element in list_ :
    print(type(element))

# Print data type of each element in list_
for element in array_list :
    print(type(element))

# Yes , Will be a differance in the data type of the elements present in list_ and array_list.
#The data type of each element in list_ is a string, while the data type of each element in array_list is an integer (int).   

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size

In [14]:
#Ans4.
import numpy as np 

ab_list =np.array([[1,2,3], [4,5,6]])
print(ab_list.shape)

print(ab_list.size)

(2, 3)
6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [16]:
#Ans5.
# Create numpy array of 3*3 matrix containing zeros only 

import numpy as np
matrix = np.zeros((3,3))
matrix 
# OR 

zero_matrix = np.zeros((3,3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [17]:
#Ans6.
import numpy as np 

# Create a 5x5 identity matrix 
identity_matrix = np.identity(5)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [22]:
# OR  Second Code 

import numpy as np
matrix = np.eye((5))
print(matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
